services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    command: -d try-db -u academic
  db:
    image: postgres:12
    container_name: postgres-odoo16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  # postgresql:
  #   image: postgres:16
  #   container_name: bpay-postgres
  #   # restart: always
  #   environment:
  #     POSTGRES_DB: db_bpay
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1sampai8
  #   ports:
  #     - "5432:5432"